### ISSUE TITLE
How to make Google drive a better place

### ISSUE THREAD

**Issue by andrew179** [andrew179/IT2_DDVS#3]
[Advice1.txt](https://github.com/andrew179/IT2_DDVS/files/1984404/Advice1.txt)

![vidish-samaya-bolshaya-oshibka-kotoruyu-dopuskayut-lyudi-kotorye-ne-umeyut-pravilno-est-burger-nepravilnaya-hvatka_1642702604](https://user-images.githubusercontent.com/29860311/39764360-293511f2-52e8-11e8-877c-d63e6a613313.jpg)

-
Number of servers | Number of users
------------ | -------------
2 | 1000
8 | 4000
16 | 80000

**Comment by yurainua82** [comment]
Good Idea Bro!
